CustomerPortal/CustomerPortal/Site/IGT.CustomerPortal.MVC/IGT.CustomerPortal.MVC/Controllers/ConceptController.cs
using IGT.CustomerPortal.API.DTO.Response;
using IGT.CustomerPortal.MVC.Exceptions;
using IGT.CustomerPortal.MVC.Service;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace IGT.CustomerPortal.MVC.Controllers
{
    [Authorize]
    public class ConceptController : PortalControllerBase
    {
        public async Task<ActionResult> Index()
        {
            string token = AccessToken;
            IEnumerable<GameResponse> list;
            try
            {
                list = await new GameService(token).ListGames();
            }
            catch
            {
                throw new DataSourceException();
            }

            SetPageTitle("Lottery Concepts");
            ActiveMenu = "concept";

            return View(list);
        }

        public async Task<ActionResult> Detail(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index");
            }

            string token = AccessToken;
            GameResponse model;
            try
            {
                model = await new GameService(token).GetGame(id);
            }
            catch
            {
                throw new DataSourceException();
            }

            SetPageTitle($"Lottery Concepts;{model.Name}", ";");
            ActiveMenu = "concept";

            return View(model);
        }
    }
}

CustomerPortal/CustomerPortal/Site/IGT.CustomerPortal.MVC/IGT.CustomerPortal.MVC/Controllers/FavoriteController.cs
using IGT.CustomerPortal.API.DTO.Response;
using IGT.CustomerPortal.MVC.Exceptions;
using IGT.CustomerPortal.MVC.Models;
using IGT.CustomerPortal.MVC.Service;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace IGT.CustomerPortal.MVC.Controllers
{
    [Authorize]
    public class FavoriteController : PortalControllerBase
    {
        // GET: Favorite
        public async Task<ActionResult> Index()
        {
            string token = AccessToken;
            IEnumerable<GameResponse> list;
            try
            {
                list = await new FavoriteService(token).List();
            }
            catch
            {
                throw new DataSourceException();
            }

            SetPageTitle("Favorites");
            ActiveMenu = "favorite";

            return View(list);
        }

        [HttpPost]
        public async Task<ActionResult> Toggle(IdRequestViewModel model)
        {
            if (string.IsNullOrEmpty(model?.Id))
            {
                return new EmptyResult();
            }

            string token = AccessToken;
            GameResponse response;
            try
            {
                response = await new GameService(token).GetGame(model.Id);
                if (!response.IsInFavorites)
                {
                    await new FavoriteService(token).Add(model.Id);
                }
                else
                {
                    await new FavoriteService(token).Delete(model.Id);
                }
                response = await new GameService(token).GetGame(model.Id);
            }
            catch
            {
                throw new DataSourceException();
            }

            return View(response);
        }

    }
}

CustomerPortal/CustomerPortal/Site/IGT.CustomerPortal.MVC/IGT.CustomerPortal.MVC/Views/Favorite/Index.cshtml
@model IEnumerable<IGT.CustomerPortal.API.DTO.Response.GameResponse>
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

@section styles {
    <link href="~/Content/igt-concept.css" media="all" rel="stylesheet" type="text/css" />
}

<div class="row">

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <div class="col-lg-2 col-md-4 mb-4">
                <div class="card shadow">

                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-white">@item.Name</h6>
                    </div>

                    <div class="card-body">
                        <a href="@Url.Action("Detail", "Concept", new { id = item.Id.ToString() })">
                            <img class="concept-thumb hvr-float" src="@item.Concepts.First().Path" />
                        </a>
                    </div>
                </div>
            </div>
        }
    }

</div>

@section scripts {
    <script>
    </script>
}

CustomerPortal/CustomerPortal/Site/IGT.CustomerPortal.MVC/IGT.CustomerPortal.MVC/Views/Favorite/Toggle.cshtml
@model IGT.CustomerPortal.API.DTO.Response.GameResponse
@{
    Layout = null;
}
<a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" data-id="@Model.Id">
    <i class="fas fa-bookmark fa-sm text-white-50"></i>&nbsp;@(Model.IsInFavorites ? "Remove from Favorites" : "Add to Favorites")
</a>